"use client";

import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Inter } from "next/font/google";
import { useRouter } from "next/navigation";
import { AuthContextProvider, useAuth } from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const { user } = useAuth();
  const router = useRouter();

  // Redirect to login if user is not authenticated
  if (router.pathname === "/profile" && !user) {
    router.push("/login");
    return null;
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Navbar />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
