import "./globals.css";
import { Outfit } from 'next/font/google'
import { notFound } from "next/navigation";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import AddProject from "@/components/helper/AddProject";
import Toaster from "@/components/helper/Toaster";
import Providers from "@/providers";
// import Providers from "@/components/helper/ProviderTheme";
// import ThemeButton from "@/components/theme/ThemeButton";

const outfit = Outfit({ subsets: ["latin"], variable: '--font-outfit',});



export const metadata = {
  title: "OpenHanded",
  description: "Generated by OpenHanded team",
  icons: {
    icon: "/favicon.ico",
  },
};

// export function generateStaticParams() {
//   return [{ locale: "en" }, { locale: "tr" }];
// }

// export async function LocaleLayout({ children, params: { locale } }) {
//   let messages;
//   try {
//     messages = (await import(`../../messages/${locale}.json`)).default;
//   } catch (error) {
//     notFound();
//   }
// }

async function RootLayout({ children, params: { locale } }) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body>
        <Providers
          className={`${outfit.variable} font-sans`}
          locale={locale}
          messages={messages}
        >
          {/* <ThemeButton /> */}

          <Nav />
          <div>{children}</div>
          <Footer />
          <AddProject />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
